### ISSUE TITLE
Can't set folder size

### ISSUE THREAD

**Issue by UInt2048** [PoomSmart/PadGrid#1]
In Anywhere Widgets for iPad 1.1, the folder size was 4x5.

Is there any way you could add the functionality to change folder size to PadGrid? It's a little ridiculous that on my iPhone, I can use a 6x7 folder (using Folded) but on my larger iPad, I have to settle for 4x4...

**Comment by PoomSmart** [comment]
I take that Folded isn't compatible with iPad?

**Comment by UInt2048** [comment]
@PoomSmart At least not with my iPad setup, and I can't figure out why. It's not officially compatible with iOS/iPadOS 14, or being updated, so it's kind of a hit-or-miss thing, I guess.

Anyways, I would really appreciate it if any option to increase folder size were added, to this tweak or a separate tweak.
