### ISSUE TITLE
Recommended grid

### ISSUE THREAD

**Issue by HackZy01** [PoomSmart/PadGrid#3]
The grid recommended by this tweak for anywhere widgets is very broken on iPad 8th generation

**Comment by HackZy01** [comment]
![image](https://user-images.githubusercontent.com/77678316/202005687-14af867f-99d0-4f04-bd76-69f18ac18a37.png)

**Comment by HackZy01** [comment]
Not only does it break the Today view, because you can't drag anything in there and if there was stuff there isn't anymore, the widgets overlap each other or other icons

**Comment by HackZy01** [comment]
Before:
![image](https://user-images.githubusercontent.com/77678316/202005871-58f0658b-a54f-439d-89ae-f750f8e3a36a.png)

**Comment by PoomSmart** [comment]
The placements of the widgets have to be very specific for the UI to look good. You are probably looking for placing the widgets at the edge.
