### ISSUE TITLE
Cannot install due to Gsc.iPad

### ISSUE THREAD

**Issue by skelitonlord** [PoomSmart/PadGrid#4]
iPad 9th gen
iPadOS 15.1  
XinaA15 jailbreak
Screenshot taken on said iPad

![image](https://user-images.githubusercontent.com/6839836/207400576-1ad8d522-b663-469d-8f51-f3c0746c5963.png)

**Comment by PoomSmart** [comment]
https://www.reddit.com/r/jailbreak/comments/zjt200/tutorial_if_youre_having_problems_on_xinaa15_try/
